name: walleti
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_awesome_calculator: ^1.0.0+1
  # State
  flutter_riverpod: ^2.4.2
  shared_preferences: ^2.2.1
  ## Utils
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  ## Local database
  drift: ^2.13.1
  sqlite3_flutter_libs: ^0.5.18
  ## Animations
  flutter_animate: ^4.2.0+1
  equatable: ^2.0.5
  # flutter_localizations:
  #   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.13.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
