name: walleti
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ## Ui
  flutter_awesome_calculator: ^1.0.0+1
  ## State
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  ## Local database
  drift: ^2.13.1
  sqlite3_flutter_libs: ^0.5.18
  shared_preferences: ^2.2.1
  ## Animations
  flutter_animate: ^4.2.0+1
  ## Dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  ## Utils
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  equatable: ^2.0.5
  # flutter_localizations:
  #   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  drift_dev: ^2.13.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
